version: '3.8'

services:
  nextjs:
    container_name: meeting_room_nextjs
    image: nextjs-docker
    build: ./nextjs-meetingroom
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Seoul
      - API_BASE_URL=http://fastapi:8000 # FastAPI 서비스와 통신
      - SESSION_SECRET=kFusfikiDG/E18VPhbDG+uPhc6wW1s9kmeNBNlVoqE4=
    depends_on:
      - fastapi

  fastapi:
    container_name: meeting_room_fastapi
    image: fastapi
    build: ./meeting-room-api
    environment:
      - SQLALCHEMY_DATABASE_URL=mysql+pymysql://root:rootpassword@mysql:3306/nextjs_db
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=dsm1234!
      - ADMIN_DEPARTMENT=ADMIN
    expose:
      - "8000"
    depends_on: 
      mysql:
        condition: service_healthy

  mysql:
    container_name: meeting_room_mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nextjs_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_data: